### ISSUE TITLE
Nether portal teleports to nether instead of destination. (video included)

### ISSUE THREAD

**Issue by Tomasan7** [sekwah41/Advanced-Portals#228]
So I have AdvancedPortals portal on spawn. The portal is made of NETHER_PORTAL portal block and has set a destination. But when you walk into it, it blinks (not in vid, for some reason) with a correct destination, but 90% of time it teleports you to nether instead of the set destination. Also I have 

Here is **config.yml**:
```
UseOnlyServerMadeAxe: true
AxeItemId: IRON_AXE
CanBuildPortalBlock: true
PortalProtection: false
PortalProtectionArea: 5
DefaultPortalTriggerBlock: NETHER_PORTAL
StopWaterFlow: true
ShowSelectionBlockID: RED_STAINED_GLASS
WarpParticles: 0
WarpSound: 0
ShowBungeeWarpMessage: false
ShowSelectionShowDuration: 10
WarpMessageDisplay: 0
UseWarpPrefix: true
UseCustomPrefix: false
CustomPrefix: '&a[&eAdvancedPortals&a]'
CustomPrefixFail: '&c[&7AdvancedPortals&c]'
BlockSpectatorMode: false
PortalCooldown: 5
ThrowbackAmount: 0.7
DisableGatewayBeam: false
CommandLevels: opcb
ConfigVersion: true
```

Here is **portals.yml**:
```
...
Spawn-Creative:
  world: Spawn
  triggerblock: NETHER_PORTAL
  destination: Creative
  pos1:
    X: 14
    Y: 73
    Z: 11
  pos2:
    X: 10
    Y: 69
    Z: 11
...
```

Here is **destionations.yml**:
```
...
Creative:
  world: creative
  pos:
    X: 27.5
    Y: 61.0
    Z: -44.5
    pitch: 0
    yaw: 0
...
```

Here is evidence video: https://youtu.be/ORG7J6Xe5PM
(the other portal is without desti, but with command and works fine)

You can test it by yourself on **mc.survivalcraft.cz** just register and then use **/spawn** command, and you should be at the same place as in video.

EDIT: Now I figured out, that it works just fine in creative.

EDIT2: After a couple more research, this is what I found out:
![AdvancedPortalsDiagram](https://user-images.githubusercontent.com/47734291/101260471-7d97f280-3730-11eb-9d64-54ef952f1536.png)
