### ISSUE TITLE
Users appearing in the wrong destination cross world

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#276]
Possible multiverse issue,

Example portals.yml that has the issue 
```
main_resource:
  world: MainWorld
  triggerblock: AIR
  destination: resource
  bungee: resource
  pos1:
    X: -637
    Y: 68
    Z: -1865
  pos2:
    X: -637
    Y: 65
    Z: -1868
canvas_main:
  world: aloha_canvas_world
  triggerblock: AIR
  destination: main
  pos1:
    X: 0
    Y: 65
    Z: 4
  pos2:
    X: -1
    Y: 64
    Z: 4
creative_main:
  world: aloha_creative_world
  triggerblock: AIR
  destination: main
  pos1:
    X: 153
    Y: 7
    Z: -272
  pos2:
    X: 150
    Y: 3
    Z: -272
oldtonew:
  world: MainWorld
  triggerblock: AIR
  destination: main
  pos1:
    X: 98
    Y: 70
    Z: 12
  pos2:
    X: 98
    Y: 67
    Z: 10
maze:
  world: MainWorld
  triggerblock: AIR
  destination: maze
  bungee: activity
  pos1:
    X: -596
    Y: 66
    Z: -1652
  pos2:
    X: -598
    Y: 60
    Z: -1652
    ```
