### ISSUE TITLE
Ridden Entities Deleted Upon Teleport

### ISSUE THREAD

**Issue by ZorudaRinku** [sekwah41/Advanced-Portals#305]
Ridden entities are completely deleted upon entering a portal
You mentioned they might be going to the nether but the nether is disabled on this server so potentially it's just deleting them

Purpur 1.17.1 Build 1428
Waterfall for 1.17.1
Advanced Portals version 0.7.1

Server.properties
```
allow-nether=false
```

bukkit.yml
```yaml
allow-end: false
```

https://user-images.githubusercontent.com/13283879/145696089-78958850-ad1b-4291-9150-1d7c36437899.mp4

Start of convo:
https://discord.com/channels/168282484037910528/249757652664582161/919122169705938974

Portal on server 1:
```yaml
Wild:
  world: world
  triggerblock: WATER
  destination: wildspawn1
  bungee: Wild
  pos1:
    X: 15
    Y: 68
    Z: 15
  pos2:
    X: -15
    Y: 62
    Z: -15
```

Destination on server 2:
```yaml
wildspawn1:
  world: world
  pos:
    X: 0.5
    Y: 63.0
    Z: 5.5
    pitch: 0
    yaw: 0
```

Config on server 1:
```yaml
ConfigVersion: 0.5.13
UseOnlyServerMadeAxe: false
AxeItemId: IRON_AXE
CanBuildPortalBlock: true
PortalProtection: true
PortalProtectionArea: 5
DefaultPortalTriggerBlock: PORTAL
StopWaterFlow: false
ShowSelectionBlockID: RED_STAINED_GLASS
WarpParticles: 1
WarpSound: 1
ShowBungeeWarpMessage: false
ShowSelectionShowDuration: 10
WarpMessageDisplay: 2
UseWarpPrefix: true
UseCustomPrefix: false
CustomPrefix: '&a[&eAdvancedPortals&a]'
CustomPrefixFail: '&c[&7AdvancedPortals&c]'
BlockSpectatorMode: false
PortalCooldown: 5
ThrowbackAmount: 0.7
DisableGatewayBeam: true
CommandLevels: opcb
CommandLogs: true
ForceEnableProxySupport: false
ProxyTeleportDelay: 0
```
