### ISSUE TITLE
DeluxeMenues GUI flashes (does not stay open)

### ISSUE THREAD

**Issue by Kanin** [sekwah41/Advanced-Portals#341]
https://kanin.cannot.date/2022/12/31/g0so.mp4

```yml
rtp:
  world: world_spawn
  triggerblock: NETHER_PORTAL
  pos1:
    X: -60
    Y: 46
    Z: 23
  pos2:
    X: -72
    Y: 22
    Z: 23
  portalArgs:
    command:
      '1': dm open all
  ```
