### ISSUE TITLE
Conditions possibly not working

### ISSUE THREAD

**Issue by Hezkore** [sekwah41/Advanced-Portals#556]
I have this condition:
```
  conditions:
  - "%checkitem_amount_nameequals:Test\ Thing%>=1"
```
And despite having that item on me, I am being rejected from the portal.

I've tested so that the commend is correct via a scoreboard plugin which also uses the placeholderAPI, using this line:
```
      text:
      - "%checkitem_amount_nameequals:Test\ Thing%"
```
And I can see that it returns the correct amount.

Am I missing something here?

**Comment by TreemanKing** [comment]
It should work fine. Is there a reason you are using a "\" as that may. contribute to it?

**Comment by sekwah41** [comment]
usualy "\ " is used to indicate a space in a variable, I assume this would be the same here? Though I don't believe that's needed given how you coded the split for the condition.

**Comment by Hezkore** [comment]
Yes, it's there for the space, and is required for the other plugin to correctly detect the item.
However, I tried without the `\` as well, and the portal still does not work.

Here's the Portal file:
```
args:
  name:
  - other_portal
  triggerblock:
  - END_PORTAL
  proxy:
  - server3
  destination:
  - start
  conditions:
  - "%checkitem_amount_nameequals:Test Thing%>=1"
maxLoc:
  posX: -7
  posY: 82
  posZ: 8
  worldName: world
minLoc:
  posX: -8
  posY: 82
  posZ: 9
  worldName: world
```
Server has been fully restarted since the portal file was created.

And in-game _(on 1.21.4)_ I give myself the item like this:
`/give @s paper[custom_name='"Test Thing"']`

The scoreboard plugin sees the item and display `1` correctly.
But going through the portal I get:
`[AdvancedPortals]The conditions to activate this portal have not been met`
